// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5wdgmW1jKJ6SAH6CFwU_7V6YSm27IGz8',
    appId: '1:941023730150:web:a5a25dbc2a163892169e27',
    messagingSenderId: '941023730150',
    projectId: 'gmd-ind4-platform-t',
    authDomain: 'gmd-ind4-platform-t.firebaseapp.com',
    databaseURL: 'https://gmd-ind4-platform-t-default-rtdb.firebaseio.com',
    storageBucket: 'gmd-ind4-platform-t.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvaNtTe1Jrk9ydHn1-WasPmH8fO6IpbNU',
    appId: '1:941023730150:android:f7c99d8109741f16169e27',
    messagingSenderId: '941023730150',
    projectId: 'gmd-ind4-platform-t',
    databaseURL: 'https://gmd-ind4-platform-t-default-rtdb.firebaseio.com',
    storageBucket: 'gmd-ind4-platform-t.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO4e-4ONss_2jCfYo0_NOrMGLRNk7O2XY',
    appId: '1:941023730150:ios:f401ffde05d9c208169e27',
    messagingSenderId: '941023730150',
    projectId: 'gmd-ind4-platform-t',
    databaseURL: 'https://gmd-ind4-platform-t-default-rtdb.firebaseio.com',
    storageBucket: 'gmd-ind4-platform-t.appspot.com',
    iosClientId: '941023730150-ochp54d9n2lf711slg34tol22i9hab46.apps.googleusercontent.com',
    iosBundleId: 'Zebra.Technologies.iotDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO4e-4ONss_2jCfYo0_NOrMGLRNk7O2XY',
    appId: '1:941023730150:ios:f401ffde05d9c208169e27',
    messagingSenderId: '941023730150',
    projectId: 'gmd-ind4-platform-t',
    databaseURL: 'https://gmd-ind4-platform-t-default-rtdb.firebaseio.com',
    storageBucket: 'gmd-ind4-platform-t.appspot.com',
    iosClientId: '941023730150-ochp54d9n2lf711slg34tol22i9hab46.apps.googleusercontent.com',
    iosBundleId: 'Zebra.Technologies.iotDashboard',
  );
}
